import fs from 'node:fs';
import * as E from '../../engine.mjs';
const prefix = 'S6 S7 S8 H5 C3 C4 H3 D4 D5 S11 X0 D9 H2'.split(' ');
const cards = E.deck();
const start = E.createGame('revised', [...prefix.map(id => cards.find(c => c.id === id)), ...cards.filter(c => !prefix.includes(c.id))]);
let s = start;
const actions = [{type:'keep'},{type:'draw'},{type:'royal',index:2},{type:'draw'},{type:'draw'},{type:'place',index:4},{type:'draw'},{type:'move',from:4,index:8}];
const states = actions.map(a => (s = E.act(s,a)));
actions.push({type:'royal',index:E.royalSlots(s)[0]}); states.push(s = E.act(s,actions.at(-1)));
actions.push({type:'armour',index:E.armourSlots(s)[0]}); states.push(s = E.act(s,actions.at(-1)));
const classic = E.createGame('classic',cards);
// Additional synthetic but card-conserving control fixtures.
const extract = structuredClone(states[6]);
const ace = extract.deck.findIndex(c => c.rank === 1);
extract.ploys.push(...extract.deck.splice(ace,1));
const extracted = E.act(extract,{type:'extract',index:4});
const blockedClassic = structuredClone(states[6]);
blockedClassic.mode = 'classic';
blockedClassic.deck.push(...blockedClassic.ploys.splice(0));
const reset = E.act(blockedClassic,{type:'reset',index:4});
const emptyClassic = structuredClone(reset);
emptyClassic.grid[0].unshift(...emptyClassic.deck.splice(0));
const refilled = E.act(emptyClassic,{type:'refill',index:0});
const victory = E.createGame('revised',cards);
victory.grid = Array.from({length:9},()=>[]);
victory.grid[0] = [cards.find(c=>c.id==='S6')];
victory.grid[3] = [cards.find(c=>c.id==='H5')];
victory.royals = cards.filter(E.royal).map(card=>({card,armour:0,armourCards:[],dead:true}));
victory.royals[0].dead=false;
victory.pending=cards.find(c=>c.id==='C2');
victory.ploys=[]; victory.queue=[]; victory.stage='play';
victory.deck=cards.filter(c=>!E.royal(c)&&!['S6','H5','C2'].includes(c.id));
const won=E.act(victory,{type:'place',index:6});
fs.writeFileSync(process.argv[2], JSON.stringify({start, classic, extract, extracted, blockedClassic, reset, emptyClassic, refilled, victory, won, replacement:E.act(start,{type:'replace',index:0}), actions, states}));
